# Generated by Django 3.2 on 2021-04-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_conversion', models.FloatField()),
                ('a_grade_proportion', models.FloatField()),
                ('uplift', models.FloatField()),
                ('days_max', models.IntegerField()),
                ('calls_per_day', models.IntegerField()),
            ],
        ),
    ]
